# Generated by Django 2.2.10 on 2020-03-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('perempuan', 'Perempuan')], default='pria', max_length=10)),
                ('price', models.CharField(max_length=5)),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
    ]
